// Categorías especializadas en ropa: "sexo - tipo prenda"
export const CLOTHING_CATEGORIES = [
  'Hombre - Camiseta',
  'Hombre - Polo',
  'Hombre - Camisa',
  'Hombre - Pantalón',
  'Hombre - Jean',
  'Hombre - Short',
  'Hombre - Bermuda',
  'Hombre - Chaqueta',
  'Hombre - Casaca',
  'Hombre - Hoodie',
  'Hombre - Suéter',
  'Hombre - Ropa Interior',
  'Hombre - Pijama',
  'Hombre - Ropa Deportiva',
  'Mujer - Blusa',
  'Mujer - Polo',
  'Mujer - Camisa',
  'Mujer - Camiseta',
  'Mujer - Pantalón',
  'Mujer - Jean',
  'Mujer - Falda',
  'Mujer - Short',
  'Mujer - Vestido',
  'Mujer - Chaqueta',
  'Mujer - Casaca',
  'Mujer - Hoodie',
  'Mujer - Suéter',
  'Mujer - Ropa Interior',
  'Mujer - Pijama',
  'Mujer - Ropa Deportiva',
  'Niño - Camiseta',
  'Niño - Polo',
  'Niño - Pantalón',
  'Niño - Short',
  'Niño - Ropa Interior',
  'Niño - Pijama',
  'Niña - Blusa',
  'Niña - Camiseta',
  'Niña - Pantalón',
  'Niña - Falda',
  'Niña - Vestido',
  'Niña - Short',
  'Niña - Ropa Interior',
  'Niña - Pijama',
  'Unisex - Gorra',
  'Unisex - Sombrero',
  'Unisex - Bufanda',
  'Unisex - Guantes',
  'Unisex - Calcetines',
  'Unisex - Medias'
] as const;

export type ClothingCategory = typeof CLOTHING_CATEGORIES[number];
